// constants/roles.js

const ROLES = {
  SUPER_ADMIN:  "SUPER_ADMIN",
  ADMIN:        "ADMIN",
  COORDINATOR:  "COORDINATOR",
  SELLER:       "SELLER",
  FINANCE:      "FINANCE",
  MARKETING:    "MARKETING",
  WAREHOUSE:    "WAREHOUSE",
};

const MODULE_ACCESS = {
  // 🚀 AGREGA ESTAS DOS LÍNEAS:
  dashboard:  [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  alerts:     [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.COORDINATOR, ROLES.SELLER, ROLES.FINANCE, ROLES.WAREHOUSE, ROLES.MARKETING],
  
  finance:    [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.COORDINATOR, ROLES.FINANCE],
  marketing:  [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.COORDINATOR, ROLES.MARKETING],
  inventory:  [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.COORDINATOR, ROLES.WAREHOUSE],
  orders:     [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.COORDINATOR, ROLES.SELLER, ROLES.FINANCE],
  superadmin: [ROLES.SUPER_ADMIN],
  users:      [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  audit:      [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.COORDINATOR],
};

module.exports = { ROLES, MODULE_ACCESS };